# Generated by Django 5.0 on 2024-01-02 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plant_guide/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Planta',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('idplanta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('guia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyects.guias')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyects.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='usuarios',
            field=models.ManyToManyField(through='Proyects.UsuarioPlanta', to=settings.AUTH_USER_MODEL),
        ),
    ]
