# Generated by Django 5.0 on 2024-01-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proyects.tipo_planta'),
        ),
    ]
