# Generated by Django 4.2.7 on 2023-11-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloPrueba',
        ),
    ]
