# Generated by Django 4.2.6 on 2023-11-30 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0002_delete_modeloprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_planta', models.CharField(max_length=200)),
                ('fecha_riego', models.DateField()),
                ('comentario', models.TextField()),
                ('ruta_imagen', models.ImageField(upload_to='imagenes/')),
                ('valor_humedad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SocialCause',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
