# Generated by Django 5.0 on 2024-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0002_planta_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_humedad', models.CharField(max_length=4)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
