# Generated by Django 5.0 on 2023-12-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0003_guias_planta_plantaregistro_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyects.guias'),
        ),
        migrations.AlterField(
            model_name='guias',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='UsuarioPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyects.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyects.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='usuarios',
            field=models.ManyToManyField(through='Proyects.UsuarioPlanta', to='Proyects.usermodel'),
        ),
    ]
